spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: false
  datasource:
    url: jdbc:mysql://localhost:3306/mywebgameproject?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 1234
  h2:
    console:
      enabled: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: id
            client-secret: secret
            scope:
              - email
              - profile
# jwt
jwt:
  issuer: a
  secret_key: b

