server:
  port: 5000 <- aws 배포를 위한 주요 포트 번호
jwt:
  issuer: jwt 작성자
  secret_key: jwt 비밀키

spring:
  #jpa
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        ddl-auto: none <- 스프링 부트에서 데이터베이스와 테이블을 만들지 않으므로 none로 설정함
    defer-datasource-initialization: true
  #datasource
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # DB 이름은 RDS의 기본 데이터베이스 이름(ebdb)이 아닌 내가 sql문으로 생성한 DB 이름으로 해도된다.
    url: jdbc:mysql://RDS의 엔드포인트값:3306/프로젝트에서 사용되는 DB이름?characterEncoding=UTF-8 <- ?characterEncoding=UTF-8 으로 utf-8 설정하여 한글 사용을 가능하게 한다.
    username: RDS에 설정한 유저이름
    password: RDS에 설정한 비밀번호
  #oauth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 구글 Oauth로그인을 위한 id 값
            client-secret: 구글 Oauth로그인을 위한 secret key 값
            scope:
              - email
              - profile